# from https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/appengine/standard/flask/hello_world/app.yaml

runtime: python310
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
