# from https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/appengine/standard/flask/hello_world/app.yaml

runtime: custom
env: flex
# entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker kitsune_app.main:app
# entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker kitsune_app.main:app
