version: '3'
services:
  kitsune:
    image: kitsune-api:latest
    container_name: kitsune-api
    # We use docker-compose in local since we have to override the command from the Dockerfile with the --reload flag
    command: "uvicorn kitsune_app.main:app --host 0.0.0.0 --port 8080 --reload"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/firebase-credentials
    secrets:
      - firebase-credentials
    build:
      context: .
      dockerfile: Dockerfile
    restart: always

    ports:
      - 8180:8080
    volumes:
      - .:/app

secrets:
  firebase-credentials:
    file: ./firebase-adminsdk-credentials.json